ethNode: 
  url: https://pokeapi.co/api/v2/pokemon/ditto
  port: 443 
  connectionTimeout: 2000
  readTimeout: 5000
logging:
  level: INFO 
  # appenders:
  #   - type: file
  #     currentLogFilename: /tmp/dropwizardTest.log
  #     threshold: INFO 
  #     queueSize: 512
  #     archive: true
  #     archivedLogFilenamePattern: /tmp/dropwizardTest-%d.log
  #     archivedFileCount: 5
  #     timeZone: UTC
  #     logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m%n%rEx"
  #     bufferSize: 8KiB
  #     immediateFlush: true
  #   - type: file
  #     currentLogFilename: /tmp/dropwizardTest_debug.log
  #     threshold: DEBUG 
  #     queueSize: 512
  #     archive: true
  #     archivedLogFilenamePattern: /tmp/dropwizardTest_debug-%d.log
  #     archivedFileCount: 5
  #     timeZone: UTC
  #     logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m%n%rEx"
  #     bufferSize: 8KiB
  #     immediateFlush: true
defaultName: Stranger
template: Hello, %s!
